instill_sdk/__init__.py, poetry.lock, pyproject.toml
Because
- fail import due to submodule import path
This commit
- update to use system agnostic path for protogen submodule
=> chore: fix submodule import path

instill/resources/connector.py, instill/resources/model.py, janky-integration-test.py
Because
- add `instill model` connector test
This commit
- add `instill model` connector test
- bump protogen-python
=> test(integration): add instill model connector

README.md, instill/clients/client.py, instill/resources/model.py, integration-test.py
Because
- provide guides on how to use this `SDK`
This commit
- add usage in `README`
=> docs(readme): add usage in README

instill/clients/connector.py, instill/clients/mgmt.py, instill/clients/model.py, instill/clients/pipeline.py
Because
- metadata will be overwritten if switch `instance`
This commit
- fix metada overwrite
=> fix(clients): fix metadata overwrite

README.md, instill/clients/connector.py, instill/clients/model.py, instill/resources/connector_ai.py, instill/resources/operator.py
Because
- adopt model connector config namepsace
- adopt new operator id
This commit
- adopt model connector config namepsace
- adopt new operator id
Resolves INS-2231
=> refactor(clients,resources): adopt model connector and operator namespace

instill/helpers/ray_helper.py
Because
- improve usability of the helper functions
This commit
- remove function decorators
- add ray model config class
=> refactor(ray): remove func decorators and add config class

instill/helpers/ray_config.py
Because
- account for cloud env
This commit
- add ray addr to argparser
=> refactor(ray): add ray addr to argparser

instill/clients/mgmt.py, instill/clients/model.py, instill/clients/pipeline.py
Because
- some api endpoints are missing from the current clients
This commit
- add missing endpoints
- adopt better type hinting
- bump protogen-python
=> refactor(clients,proto): add missing endpoints and add better type hint

instill/clients/client.py, instill/clients/mgmt.py, instill/clients/pipeline.py, instill/resources/pipeline.py
Because
- cannot get user
- cannot trigger pipeline with async model
This commit
- add `users/me` alias in get user method
- fix trigger async method
=> fix(client): fix async pipeline trigger and get user

instill/clients/instance.py, instill/clients/mgmt.py, instill/clients/model.py, instill/clients/pipeline.py, instill/resources/__init__.py, instill/resources/connector.py, instill/resources/operator.py, instill/resources/pipeline.py, instill/resources/recipe.py, instill/tests/test_client.py, tests/test_client.py
Because
- VDP now supports organization endpoints
- VDP will step up to beta release
This commit
- adopt organization endpoints for VDP
- adopt beta version endpoints
=> feat(org): adopt organization endpoints for VDP

instill/resources/connector_ai.py, instill/resources/connector_airbyte.py, instill/resources/connector_blockchain.py, instill/resources/connector_data.py, instill/resources/pipeline.py
Because
- update pipeline resource validation to return bool
This commit
- update pipeline resource validation to return bool
=> chore(resources): update pipeline resource validation to return bool

instill/helpers/ray_config.py, poetry.lock
Because
- GPU resource quantities > 1 must be whole numbers.
This commit
- apply math.ceil to vram usage ratio
=> fix(ray): fix gpu resource > 1

instill/helpers/const.py, instill/helpers/ray_config.py
Because
- replica upscale is not working as expected
This commit
- apply more aggressive autoscaling config
=> refactor(ray): update autoscaling and vram config

instill/helpers/Dockerfile, instill/helpers/build.py, instill/helpers/const.py, poetry.lock, pyproject.toml
Because
- we need to provide easy-to-use script for user to build and push containerized model to desired registry
This commit
- add `docker` dependency
- add `build` module script for easy image building and pushing
=> feat(ray): support containerized model build and push

instill/helpers/Dockerfile, instill/helpers/build.py
Because
- we need to copy model weight files along with config and model.py
This commit
- update `dockerfile` to copy all files in the same directory
=> fix(dockerfile): copy all files in the same model dir

instill/resources/model.py, instill/resources/pipeline.py
Because
- We need to prevent the process from exiting in certain situations
This commit
- add silent argument in resource methods
=> chore(resources): add silent option to resource

instill/resources/model.py, instill/resources/pipeline.py
Because
- Keyword assignment is wrong
This commit
- fix silent assignments
=> chore(resources): fix silent assignments

.github/workflows/build.yml, poetry.lock, pyproject.toml
Because
- We are going to upgrade ray cluster version
This commit
- bump ray version
=> chore(deps): bump ray version

.gitignore, instill/clients/mgmt.py, instill/clients/model.py, instill/clients/pipeline.py, instill/resources/__init__.py
Because
- sdk should be up-to-date with API spec so that users could use it as API wrapper
This commit
- updated client code according to current proto def
=> feat(client): adopt latest api spec

instill/helpers/__init__.py, instill/helpers/const.py, instill/helpers/protobufs/ray_pb2.py, instill/helpers/protobufs/ray_pb2.pyi, instill/helpers/protobufs/ray_pb2_grpc.py, instill/helpers/ray_io.py
Because
- update ray proto to use `__call__` as default trigger entry to allow http request
- wrong visioninput `image` type
This commit
- update proto and fix wrong vision input type
- fix VisionInput image type
=> fix(ray): update proto and fix wrong vision input type

instill/clients/artifact.py, instill/clients/model.py, instill/clients/pipeline.py
- **feat(dep): updated proto**
- **feat(client): update client code for artifact/model/pipeline**
Because
- client code is out of date
This commit
- update client code
=> chore(main): catch up with protobuf definition

instill/clients/pipeline.py
Because
- trigger_org_pipeline_release does not work
This commit
- add release_id in input parameters and fix name in request
=> fix(vdp): fix trigger pipeline release input

instill/clients/artifact.py, instill/clients/client.py, instill/clients/mgmt.py, instill/clients/model.py, instill/clients/pipeline.py, instill/configuration/__init__.py, instill/tests/test_client.py, tests/test_client.py
related changes for documentation at https://github.com/instill-ai/instill.tech/pull/1087
Because
- users should be able to initialize service directly
This commit
- add new direct service initialization functions
=> chore(main): new direct service initialization

instill/helpers/init-templates/model.py
Because
- model template file needs to be updated to catch up with the new AI task spec
This commit
- update model template
=> chore(ray): update init template

instill/clients/client.py, instill/resources/model.py, instill/resources/pipeline.py
Because
- excessive suffix for client name
This commit
- update client naming
=> chore(client): update client naming

instill/clients/app.py, instill/clients/artifact.py, instill/clients/client.py, instill/clients/instance.py, instill/clients/pipeline.py
Because
- lack of support for app service APIs and updates in artifact 
This commit
- update by protogen and add app client
=> feat(client): update proto and add AppClient

instill/clients/pipeline.py
Because
- protobuf definition types for connection should be encapsulated for better DX
This commit
- encapsulate protobuf definition types for pipeline
=> fix(vdp): fix update pipeline parameter

instill/clients/pipeline.py
Because
- field mask needs to be updated
This commit
- update field mask
=> fix(vdp): fix update pipeline mask

instill/clients/artifact.py, instill/clients/mgmt.py, instill/clients/model.py, instill/clients/pipeline.py
Because
- protobuf definitions are updated
This commit
- update client code accordingly
=> chore(client): update protogen

instill/helpers/cli.py
Because
- better local model run performance
This commit
- update run command shmsize
=> fix(cli): update run command shmsize

instill/helpers/cli.py
Because
- update join pkg str
This commit
- update join pkg str
=> chore(cli): update join pkg str

instill/helpers/cli.py, instill/helpers/init-templates/Dockerfile
Because
- tz directory does not align between systems
This commit
- remove timezone for compatibility issue
=> fix(ray): remove timezone for compatibility issue

instill/helpers/const.py
Because
- need to update prod url
This commit
- updates prod url
=> chore(const): update HOST_URL_PROD to latest prod API url
