instill-ai/python-sdk

- .github/workflows/test.yml
- instill_sdk/clients/client.py
- instill_sdk/clients/connector.py
- instill_sdk/clients/mgmt.py
- instill_sdk/clients/model.py
- instill_sdk/clients/pipeline.py
- tests/test_client.py
Because
- allow users to authenticate with api-token for instill cloud
This commit
- add support for api-token header
> feat(auth): support api-token for instill cloud authentication

- instill_sdk/__main__.py
- instill_sdk/configuration/__init__.py
- poetry.lock
- pyproject.toml
Because
- provide better UX for configuring SDK
This commit
- unify config location for instill products
- adopt yaml config file for target hosts configuration
- adopt `pydantic` for config validation
> feat(config): adopt pydantic for yaml config validation

- instill_sdk/__main__.py
- instill_sdk/clients/client.py
- instill_sdk/clients/connector.py
- instill_sdk/clients/mgmt.py
- instill_sdk/clients/model.py
- instill_sdk/clients/pipeline.py
- instill_sdk/configuration/__init__.py
- instill_sdk/tests/test_client.py
- tests/test_client.py
Because
- allow user to interact with multiple instances with just one client
This commit
- support multi instances in client
- add missing functions supported in API
> refactor(clients): update client interface to support multi instances

- instill_sdk/__main__.py
- instill_sdk/clients/__init__.py
- instill_sdk/clients/base.py
- instill_sdk/clients/client.py
- instill_sdk/clients/connector.py
- instill_sdk/clients/mgmt.py
- instill_sdk/clients/model.py
- instill_sdk/clients/pipeline.py
- instill_sdk/resources/__init__.py
- instill_sdk/resources/connector.py
- instill_sdk/resources/connector_ai.py
- instill_sdk/resources/connector_blockchain.py
- instill_sdk/resources/connector_data.py
- instill_sdk/resources/model.py
- instill_sdk/resources/pipeline.py
- instill_sdk/tests/test_client.py
- instill_sdk/utils/error_handler.py
- janky-integration-test.py
- tests/conftest.py
- tests/test_client.py
Because
- allow better UX when using and implementing `resource`
This commit
- adopt multi instance `client` in `resource`
- update `resource` interface
- update integration-test
> refactor(clients,resources): adopt multi instance and update resource interaface

- instill_sdk/clients/connector.py
- instill_sdk/clients/model.py
- instill_sdk/clients/pipeline.py
- instill_sdk/resources/connector.py
Because
- remove connector's connect/disconnect in connector-backend
This commit
- remove connect/disconnect api
> refactor(connector): remove connect/disconnect

- instill_sdk/__init__.py
- instill_sdk/clients/__init__.py
- instill_sdk/clients/base.py
- instill_sdk/clients/connector.py
- instill_sdk/clients/mgmt.py
- instill_sdk/clients/model.py
- instill_sdk/clients/pipeline.py
- instill_sdk/configuration/__init__.py
- janky-integration-test.py
Because
- adopt instill core auth
This commit
- support `bearer` auth token with insecure channel as metadata
> feat(auth): adopt `Instill Core` auth

- README.md
- instill/clients/connector.py
- instill/clients/mgmt.py
- instill/clients/model.py
- instill/clients/pipeline.py
- instill/configuration/__init__.py
Because
- support both secure/insecure option in config to accommodate `Core` and `Cloud` instance
This commit
- add `secure` in config
- update `client` to adopt updated config
> refactor(config): add channel secure option in config

- instill/clients/connector.py
- instill/clients/mgmt.py
- instill/clients/model.py
- instill/clients/pipeline.py
- instill/resources/connector_ai.py
- janky-integration-test.py
Because
- require `api-token` when setting up instill model connector
This commit
- add `api-token` in clients
> chore(clients): add token in clients

- instill/resources/__init__.py
- instill/resources/connector.py
- instill/resources/model.py
- instill/resources/operator.py
- instill/resources/pipeline.py
- instill/resources/recipe.py
- instill/utils/error_handler.py
- integration-test.py
- janky-integration-test.py
Because
- provide better UX for creating components for pipeline
This commit
- support component creation from connector
- add function for recipe creation
- update integration-test
- add `kwarg` `silent` for error handling
Resolves INS-1911
> feat(component,recipe): support better component/recipe creation

- README.md
- instill/clients/client.py
- instill/resources/model.py
- integration-test.py
Because
- provide guides on how to use this `SDK`
This commit
- add usage in `README`
> docs(readme): add usage in README

- README.md
- instill/clients/client.py
- integration-test.py
Because
- import client will cause `os._exit(1)` if `instill vdp` and `instill model` are not running, this is not desired
This commit
- add `is_serving()` check and warn the user if the functionalities for `instill vdp` or `instill model` wont work
- bump `protogen`
> chore(client,readme,deps):  fix client init will exit without `vdp` or `model`

- .github/workflows/publish.yml
Because
- curl pypi version response does not sort with semantic version
This commit
- use `sort -V` to properly sort semantic versioning string
> ci(workflows): fix release-please rc tag

- README.md
- instill/clients/client.py
- instill/clients/connector.py
- instill/clients/constant.py
- instill/clients/mgmt.py
- instill/clients/model.py
- instill/clients/pipeline.py
- instill/configuration/__init__.py
- instill/tests/test_client.py
- tests/test_client.py
Because
- avoid error exit if `default` instance not found
This commit
- fallback to the first instance entry in config file if `default` not found
> chore(clients): optimize instance switching

- .github/labeler.yml
Because
- emoji label might cause issues
This commit
- update github project label
> ci(labeler): update Github label

- README.md
- instill/configuration/__init__.py
- instill/utils/logger.py
Because
- avoid path collision with other `Instill` product config file
This commit
- update config file path to have product scope prefixes: `sdk/python`
> refactor(config)!: update config file path to avoid collision

- .github/workflows/publish.yml
Because
- wrong `rc` tag when major or minor version bump
This commit
- update get rc version command
> ci(workflows): fix wrong rc version when minor version bump

- instill/clients/client.py
- instill/resources/connector.py
- instill/resources/model.py
- instill/resources/pipeline.py
Because
- grpc channel not close
- overwriting `_del_` is a will cause resource deletion after script finish
This commit
- move resource function `_del_` to `delete`
- close grpc channels propely
> fix(client)!: fix wrongful delete of resources and connection not close

- instill/configuration/__init__.py
- instill/resources/pipeline.py
Because
- allow better user experience when setting target host and api token 
This commit
- make config file optional and allow setting default host and api token during runtime
- fix mandatory `recipe` argument even with existing resource
- bump protogen-python version
Resolves INS-2505
> fix(config,pipeline): allow no config file and fix required pipeline recipe

- README.md
- integration-test.py
- notebooks/story_pipeline.ipynb
Because
- the config format of start operator has been changed
This commit
- update config of start operator
> chore(test,readme,utils): update config of start operator

- instill/clients/__init__.py
- instill/clients/base.py
- instill/clients/client.py
- instill/clients/instance.py
- instill/clients/mgmt.py
- instill/clients/model.py
- instill/clients/pipeline.py
- instill/resources/connector.py
- instill/resources/model.py
- instill/resources/pipeline.py
- instill/tests/test_client.py
- tests/test_client.py
Because
- add `asyncio` support for IO bound request tasks
This commit
- add `asyncio` support in each endpoint
- refactor `client` return type to align with protobuf message
- add `instance` class to provide better type hinting
- remove global client to avoid event_loop collision between `sync` and `async` clients
- misc fixes
fixes INS-2793
fixes INS-2800
fixes INS-2142
> feat(client)!: support asyncio and add better client type hint

- instill/clients/pipeline.py
- instill/resources/connector.py
- instill/resources/connector_ai.py
- instill/resources/connector_blockchain.py
- instill/resources/connector_data.py
- instill/resources/model.py
- instill/resources/operator.py
- instill/resources/pipeline.py
Because
- get None type from create resource method
This commit
- fix resource creating will get None type
> fix(clients,resources): fix resource creating will get None type

- instill/helpers/ray_config.py
Because
- missing ray address to init ray connection
This commit
- fix missing ray init
> fix(ray): fix missing ray init

- instill/helpers/const.py
- instill/helpers/ray_config.py
- notebooks/asyncio_example.py
Because
- some models will need packages in current directory as dependencies
This commit
- allow current working directory as runtime env
> fix(ray): allow cwd as runtime env

- instill/helpers/const.py
- instill/helpers/ray_config.py
Because
- retire non-decorator deployment method
- adjust auto scaling sensitivity
This commit
- remove non-decorator deployment config
- update auto scaling params
> refactor(ray)!: retire non-decorator deploy and update scaling config

- poetry.lock
- pyproject.toml
Because
- adopt latest ray to fix `pydantic` version lock
This commit
- adopt latest ray to fix `pydantic` version lock
> build(deps): adopt ray 2.9.0

- instill/helpers/const.py
Because
- ray auto-downscale is too aggressive, and auto-upscale is too passive
This commit
- update autoscaling config to avoid undesired scaling behaviors
> fix(ray): avoid agressive downscale and non upscale

- instill/helpers/const.py
- instill/helpers/ray_io.py
Because ... 
- This update is necessitated by the need to align our current text-generation-task schema more closely with OpenAI's task structure.
This commit .. 
1. **Enhancement of TASK_TEXT_GENERATION**: Following our discussion in [INS-2982](https://linear.app/instill-ai/issue/INS-2982/harmonizing-the-text-generation-tasks-protocol-buffer-with-the-openai), we have introduced three new fields to the `TASK_TEXT_GENERATION` protocol buffer:
- An optional `system_message` string.
- An optional `chat_history` field, now mirroring the type used in `conversation`.
- An optional `image_url` string, which is a base64 encoded string including batch dimension.
2. **Improved `extra_param` Support**: To offer enhanced functionality for the `extra_param`, we have implemented the suggestions in …
> feat(model): Update Text-Generation Task Schema to Align with OpenAI Standards 

- instill/helpers/const.py
- instill/helpers/ray_io.py
Because
- parsing prompt_images field failed on text-generation related tasks
This commit
- made prompt images optional
- fix decoding issue
> fix(model): fix image decoding issue

- instill/resources/const.py
Because
- resource schema files cannot be referenced with wrong path
This commit
- fix resource schema path
> fix(resources): fix resource schema path

- README.md
- instill/resources/connector_ai.py
- instill/resources/connector_airbyte.py
- instill/resources/connector_blockchain.py
- instill/resources/connector_data.py
- instill/resources/model.py
- instill/resources/operator.py
- instill/resources/schema/helper.py
Because
- Optional field should be discarded from `dict` if no value is deliberately set
This commit
- pop optional values with `None` instead of populating it with zero value
- adopt `dataclass` to `dict` transform inside each resource class instead of expose it to user
- update `Readme` and notebook
> refactor(resources): pop optional values with `None`

- instill/clients/pipeline.py
- instill/resources/pipeline.py
Because
- currently we dont support updating recipe in pipeline resource object
This commit
- support recipe update in pipeline resource
> feat(resources): support recipe update in pipeline resource

- instill/helpers/ray_config.py
- instill/helpers/utils.py
Because
- we want to dynamically adjust the `num_of_gpus` value for each model
This commit
- determine vram usage by file size
> feat(ray): determine vram usage by file size

- instill/helpers/const.py
Because
- application level autoscaling is not working due to wrong `application name` and `deployment name`
- we can now apply more standard autoscaling configs
This commit
- lower max concurrent queries
- lower default number of max replicas
- lower upscale factor
- lower downscale delay
- higher downscale factor
resolves ins-3133
> fix(ray): fix ray autoscaling

- instill/helpers/ray_config.py
Because
- we deprecated `triton` in model-backend, therefore the model name format is updated
This commit
- update application name
> refactor(ray): update application name

- instill/helpers/ray_config.py
Because
- GA runner does not have enough resource to run ray model tests
This commit
- lower resource allocation
> fix(ray): update default resources allocation for test

- instill/helpers/ray_config.py
Because
- `model-backend` needs `Ray` CLI to deploy dockerized application
This commit
- return deployment handle for CLI to reference
> feat(ray): add deployment handle return for ray CLI

- instill/helpers/build.py
- instill/helpers/ray_config.py
Because
- It is not practical to determine vram usage solely from model file size
This commit
- expose cpu/gpu/ram resource allocation config to user
> feat(ray): expose cpu/gpu resource allocation config

- instill/helpers/Dockerfile
- instill/helpers/build.py
Because
- It is hard to know what went wrong without build logs
- pip install tends to timeout for large packages installation
This commit
- print build logs
- add default timeout for pip package installation
> fix(ray): show build logs and add pip timeout

- instill/helpers/build.py
- instill/helpers/push.py
Because
- user may want to push to multiple registries, it is undesirable to define in `instill.yaml`
This commit
- separate `build` and `push` script
- remove `registry` from model config
> feat(ray): separate build and push functionality

- instill/helpers/build.py
Because
- Missing `CUDA_SUFFIX` ARG will cause model container to lose GPU capability
This commit
- add missing cuda suffix arg
> fix(ray): add missing cuda suffix arg

- instill/helpers/const.py
- instill/helpers/ray_config.py
Because
- We are going to support requesting different Nvidia accelerator type or even custom resource
This commit
- support configuring accelerator type or custom resource for model
Resolves INS-3967
> feat(ray): add accelerator and custom resource support

- instill/helpers/build.py
Because
- Support optional tag in config
This commit
- generate sha256 hash as tag for user if not specified in config file
> feat(ray): generate sha256 as tag if not presented

- instill/helpers/const.py
- instill/helpers/ray_config.py
Because
- model-backend needs to inject `accelerator_type` env variable at container runtime to schedule the model on the correct machine type
This commit
- support accelerator_type env variable injection at runtime
> feat(ray): inject accelerator type at runtime

- instill/helpers/build.py
- poetry.lock
- pyproject.toml
Because
- It's a better practice to do file operation in a `tmp` folder
- We adopt latest ray version for our ray server
This commit
- adopt `tempfile` for copying and building image
- upgrade `ray` to `2.10.0`
> feat(ray): use tmp folder for image building

- instill/helpers/Dockerfile
- instill/helpers/const.py
- instill/helpers/ray_config.py
Because
- We are moving to containerized model serving
This commit
- use env variable to pass through resource configs
- deprecate deploy/undeploy methods
> feat(ray): use env for resource and deprecate deploy/undeploy

- instill/helpers/build.py
Because
- Image built with `build` module may have mismatch target platform
This commit
- support target platform for image building
> fix(ray): support target platform for image building

- poetry.lock
- pyproject.toml
Because
- Ray `2.10.0` has issue with python module import path
This commit
- downgrade ray to `2.9.3`
> fix(deps): downgrade ray to avoid grpc servicer issue

- instill/helpers/ray_config.py
Because
- Missing default value might cause to the model to become unschedulable
This commit
- add default resource value if not presented
> fix(ray): fix missing default resource value

- instill/helpers/Dockerfile
Because
- We are seeing occasional hang at `ARG` statement and change the statement order seems to solve it for now, need to keep an eye on it.
This commit
- change `ARG` statement order
resolves INS-4015
> fix(dockerfile): avoid build hang at ARG statement

- .github/workflows/test.yml
- instill/helpers/const.py
- instill/helpers/ray_config.py
- samples/tinyllama-cpu/model.py
- samples/tinyllama-gpu/model.py
- samples/yolov7-cpu/model.py
- samples/yolov7-gpu/model.py
Because
- we will not expose model resource config through model decorator
This commit
- make resource config methods private
- update default autoscaling config
> refactor(ray): make model resource config private

- instill/helpers/protobufs/parse.py
Because
- writing metadata response is a burden for user
This commit
- add predefined constructors for LLM related task for better developer experience when implementing custom models
> feat(ray): add metadata and infer constructor for llm tasks

- instill/helpers/__init__.py
Because
- Some helper functions are missing from general help import path
This commit
- add missing import paths
> fix(ray): fix missing imports

- instill/helpers/Dockerfile
- instill/helpers/build.py
- instill/helpers/errors.py
- instill/helpers/push.py
- pyproject.toml
Because
- user may want to install system packages in custom models
- to execute build/push module, user has to know the exact import path
- build image with different tag involves editing the config file, which is not ideal
This commit
- build and distribute build/push modules as standalone executables
- support installing optional system packages in custom model image
- make tag as input args instead of being as a field inside config file
Resolves INS-4377
Resolves INS-4379
> feat(ray): implement standalone executable and optional system packages

- docs/requirements.txt
Because
- avoid package vulnerability 
This commit
- bump `jinja` version
> chore(deps): bump doc dep version

- instill/clients/instance.py
Because
- Response with large payload will result in
```
2024-05-09 05:24:41,357.357 WARNING  StatusCode.RESOURCE_EXHAUSTED
2024-05-09 05:24:41,357.357 WARNING  Received message larger than max (5666203 vs. 4194304)
```
This commit
- add max send/receive message length option
> fix(clients): fix message length

- instill/clients/instance.py
Because
- the original 10MB size limit is not enough.
This commit
- increase size limit to 32MB.
> chore(clients): update message length to 32MB

- instill/helpers/const.py
- instill/helpers/ray_config.py
- poetry.lock
Because
- `Ray` had deprecated and renamed some config fields for application
This commit
- update deprecated configs
> chore(deps): update upstream deprecated configs

- instill/helpers/ray_config.py
Because
- accelerator type default to fractional of `0.001` and its causing auto-scaling problems
This commit
- set custom resource ratio with `num_of_gpu`
> chore(ray): set num_of_gpu to custom resource

- instill/helpers/Dockerfile
Because
- Avoid weight copying time when config file is changed
This commit
- separate config and weights into different layers
> feat(dockerfile): separate config and weights into different layers

- instill/helpers/.dockerignore
- instill/helpers/Dockerfile
Because
- Avoid producing different image when updating config file
This commit
- exclude config file from build process
> chore(dockerfile): exclude config file from build process

- instill/helpers/Dockerfile
- instill/helpers/build.py
Because
- Currently we don't support different cuda version
- Permission issue with `--link` flag
This commit
- add `cuda_version` field in config file
- remove `--link` flag with `COPY` command
- add `--chown` to preserve owner
> feat(ray): support cuda version and fix user root permission

- pyproject.toml
Because
- In command line underscore is quite uncommon
This commit
- use hyphen instead of underscore in build/push command alias
> chore(poetry): update build/push command alias

- instill/clients/model.py
- instill/clients/pipeline.py
- instill/resources/__init__.py
- instill/resources/model.py
- instill/resources/pipeline.py
- tests/test_integration.py
Because
- Some client apps has been affected by the breaking changes within API spec, needs to update some part of api abstraction fast to continue supporting those client apps
- breaking changes has not yet all catch up, this will need to be done soon
This commit
- update api spec partially
> chore(clients,resources): fix out dated api spec and methods

- instill/__init__.py
- instill/helpers/ray_io.py
- instill/resources/__init__.py
Because
- Our protogen `model` module import name will collide with local `model.py`
This commit
- avoid module name collision by temporarily remove cwd path from `sys.path`
> fix(ray): avoid protogen module name collision with model.py

- instill/helpers/cli.py
- instill/helpers/init-templates/Dockerfile
Because
- Often time `instill-sdk` package is updated while other dependencies version stay the same
This commit
- separate sdk installation into another layer to make the build process more effiecient
> feat(ray): separate sdk installation into another layer

- instill/__init__.py
- instill/helpers/init-templates/Dockerfile
Because
- executable path is not always `""`
This commit
- rename conflicting `model.py` file name inside container
> fix(ray): revert path injection and rename model file instead

- instill/helpers/ray_io.py
Because
- The generated field names for protobuf message does not aligned between golang and python
- Task protobuf definitions are going to be retired
This commit
- use `MessageToDict` instead to parse task inputs
> fix(ray): use dict instead of protobuf message

- instill/helpers/cli.py
- instill/helpers/const.py
- instill/helpers/ray_io.py
- instill/helpers/test.py
Because
- python cli needs to provide model image self-test function
This commit
- add `run` command to provide local self-test
> feat(ray): support model image self-test

- instill/clients/model.py
- instill/clients/pipeline.py
Because
- some fields in payload are missing
This commit
- fixed create_pipeline/validate_pipeline/trigger_pipeline client functions
tested on local with code below
```
name = "test5-2"
client.pipeline_service.create_pipeline(
name,
"this is a pipeline for demo",
{
"output": {"result": {"title": "result", "value": "${variable.input}"}},
"variable": {"input": {"instillFormat": "string", "title": "input"}},
},
False,
)
client.pipeline_service.validate_pipeline(name, False)
print(
client.pipeline_service.trigger_pipeline(
name, [{"input": "hello world"}], [], False
)
)
```
output:
```
model_name = "test1"
import instill.protogen.model.model.v1alpha.model_pb2 as model_interface
model_version = "20240726"
resp = client.model_service.trigger_model(
model_name,
[
model_interface.TaskInput( …
```
> fix(client): pipeline and model client code

- poetry.lock
- pyproject.toml
Because
- Ray does not support python version `3.12`
- Some dependencies does not work on python version `3.8`
This commit
- update supported python version matrix
> chore(deps): update supported python version matrix

- instill/helpers/cli.py
- instill/helpers/init-templates/Dockerfile
Because
- currently, model image can only install instill-sdk from pypi service, which makes changes must be merged into main branch
->
- with these changes, we can make dist to build local dev wheel and instill build --sdk-wheel {path-to-wheel} to force model image to use dev version sdk, which makes the dev process much easier
This commit
- support local sdk wheel for building model image
> feat(build): support local sdk wheel for building model image

- docs/requirements.txt
- instill/clients/artifact.py
Because
- page size and page token default values for artifact should align with those in pipeline and model
This commit
- added default values for list params
> fix(client): added some parameter default values for artifact

- instill/clients/artifact.py
- poetry.lock
related to https://github.com/instill-ai/protobufs/pull/408
Because
- knowledge base renamed
This commit
- updated proto and client code
> feat(artifact): updated proto and client code

- instill/helpers/init-templates/Dockerfile
- instill/helpers/ray_io.py
Because
- model output may have unserializable data type
This commit
- fix bounding box output type
> fix(ray): fix bounding box output type

- instill/helpers/ray_io.py
Because
- `n` should always be `integer`
This commit
- fix number of sample type
> fix(ray): fix number of sample type

- instill/helpers/init-templates/Dockerfile
Because
- cache dir will cause significant storage size increase in model image
This commit
- revert storing cache dir
> fix(dockerfile): revert storing cache dir

- instill/helpers/ray_io.py
Because
- allow receiver to properly render image
This commit
- append mime type for image output
> fix(ray): append mime type for image output

- instill/clients/artifact.py
Because
- get_file_catalog file_id and file_uid can allow empty string as input
This commit
- add default value for get_file_catalog input parameters
related changes for documentation at https://github.com/instill-ai/instill.tech/pull/1087
> feat(artifact): update get_file_catalog input parameter default values

- instill/helpers/const.py
- instill/helpers/ray_io.py
Because
- `python-request` user-agent header will cause image retrieval to be blocked
This commit
- replace user-agent header
> fix(ray): replace user-agent header

- instill/helpers/ray_io.py
Because
- wrong insert position for text message content
This commit
- fix multimodal chat input
> fix(ray): fix multimodal chat input

- instill/helpers/ray_io.py
Because
- image list and message list length does not match
This commit
- fix misaligned message and image length
> fix(ray): fix misaligned message and image length

- instill/clients/client.py
- instill/clients/instance.py
- instill/clients/model.py
- instill/tests/test_client.py
- tests/test_client.py
Because
- update model client implementation
This commit
- replace `user`/`org` endpoints with `namespace` endpoint
- support target namespace for model client
- support extra metadata/header for model client
> feat(client): support target namespace and extra header

- instill/clients/__init__.py
- instill/clients/client.py
Because
- We should still support individual client initialization functions
This commit
- revive individual client initialization
> refactor(client): revive individual client initialization

- instill/clients/app.py
Because
- with some default parameter will be easier for users
This commit
- add default parameters for client function
> feat(app): update AppClient

- instill/clients/client.py
Because
- consistency with other service client
This commit
- rename app_service to app
> fix(app): rename app_service to app

- instill/clients/pipeline.py
Because
- some changes are reverted in previous release
This commit
- fix create pipeline input parameters
> fix(vdp): fix create pipeline input parameters

- instill/clients/pipeline.py
Because
- create pipeline API has new parameter
This commit
- add raw recipe to create pipeline input parameters
> chore(vdp): add raw recipe to create pipeline input parameters

- instill/clients/pipeline.py
Because
- parameter name `pipeline id` should align with other function parameter names
This commit
- rename `pipeline id`
> fix(vdp): rename create pipeline input parameters

- instill/clients/pipeline.py
Because
- some users might start to use new raw recipe parameter
This commit
- make new and old recipe parameters both work
> fix(vdp): allow empty input for recipe parameter

- instill/clients/pipeline.py
Because
- protobuf definition types for connection should be encapsulated for better DX
This commit
- encapsulate protobuf definition types for connection
> fix(vdp): fix create/update connection input parameters

- instill/clients/pipeline.py
Because
- protobuf definition types for connection should be encapsulated for better DX
This commit
- encapsulate protobuf definition types for pipeline
> chore(vdp): encap list pipeline visibility parameter

- instill/clients/pipeline.py
Because
- protobuf definition types for connection should be encapsulated for better DX
This commit
- encapsulate protobuf definition types for pipeline
> chore(vdp): add description parameter

- instill/helpers/__init__.py
- instill/helpers/ray_config.py
Because
- `30` minutes downscale delay is not suitable for testing scenario
This commit
- support shorter downscale config for test models
> feat(ray): support shorter downscale config for test models

- instill/clients/app.py
- instill/clients/artifact.py
- instill/clients/client.py
- instill/clients/mgmt.py
- instill/clients/model.py
- instill/clients/pipeline.py
- instill/configuration/__init__.py
- instill/helpers/const.py
Because
- protobuf definitions are updated
This commit
- update client code accordingly
> chore(client): update protogen and fix client

- instill/helpers/ray_io.py
Because
- semantic segmentation task output parse does not follow task schema
This commit
- fix output key
> fix(ray): fix semantic segmentation task parser

- instill/clients/pipeline.py
Because
- using dict type as response makes it easier for users to access pipeline trigger results
This commit
- return dict type instead of proto type in pipeline trigger
> feat(vdp): return dict type instead of proto type in trigger pipeline

- instill/helpers/cli.py
- instill/helpers/init-templates/Dockerfile
Because
- misalign timezone between host and model container when executing `run`
This commit
- align timezone between host and model container by mounting timezone configs
> fix(cli): align timezone between host and model container

- instill/helpers/cli.py
Because
- currently its limit to single gpu for local model inference
This commit
- support multi-gpus when running inference locally
> feat(cli): support multi-gpus when running inference locally

- docs/requirements.txt
- instill/helpers/init-templates/Dockerfile
Because
- confirmation prompt will break model image building
This commit
- add -y for apt package installation
> fix(ray): add -y for apt package installation

- instill/helpers/const.py
- instill/helpers/ray_config.py
Because
- align autoscale config
This commit
- align autoscale config
> fix(ray): align autoscale config

- .github/CODEOWNERS
Because
- repo owners update
This commit
- update the CODEOWNERS file
> ci(CODEOWNERS): assign George and Pinglin

- instill/helpers/cli.py
- instill/helpers/docker/.dockerignore
- instill/helpers/docker/Dockerfile
- instill/helpers/docker/Dockerfile.vllm
Because
- Ray runtime_env will [deprecate](https://github.com/ray-project/ray/blob/master/python/ray/runtime_env/runtime_env.py#L396-L400) `container` on 31st July, `image_uri` should be used instead.
This commit
- tackles the coming Ray change. Instead of mounting the gRPC files during runtime, we build the files directly in the image.
- improves the clarity of the Dockerfile for vllm arm64
> chore(ray): build user defined protos in image

- instill/helpers/cli.py
- instill/helpers/docker/Dockerfile
- instill/helpers/docker/Dockerfile.vllm
Because
- `pip install` will put instill-sdk in the standard anaconda3 package path.
This commit
- make editable and non-editable work together.
> fix(ray): make non-editable work with dynamic pkg import
